# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17548bc965073de3ec52e8fef76912cb8c8b3323a22edc89163ac53b4e160c5fdd4391de039dd1b6954c15dec84583ffd49303bad39279bb490167e1644358a1

test:
  secret_key_base: c82d218e90d786ba925f4d27dedf41712b19be9d71ecb8f7222b302a53678e6f03233e4a7018587b38e5b60a9197f174fc5f9c47782287316fcb3a625025b3d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
